-- Mobile support: device push registrations, calendar feeds, notification
-- preferences, account deletion requests, and identity linking.

-- ---------------------------------------------------------------------------
-- Identities
--
-- One application user may authenticate through more than one provider
-- (Google today, Apple later). Identities are separate rows so that linking a
-- second provider can never create a second resident.
-- ---------------------------------------------------------------------------

CREATE TABLE user_identities (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider     text        NOT NULL CHECK (provider IN ('google', 'apple')),
  subject      text        NOT NULL,
  email        text,
  /* Apple relays a per-app address; keep it so a later sign-in matches. */
  is_private_relay boolean NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz,
  CONSTRAINT user_identities_provider_subject_key UNIQUE (provider, subject)
);

CREATE INDEX user_identities_user_idx ON user_identities (user_id);
CREATE INDEX user_identities_email_idx ON user_identities (lower(email));

-- Backfill the identity that `users.auth_user_id` already represents.
INSERT INTO user_identities (user_id, provider, subject, email, last_login_at)
SELECT id, 'google', auth_user_id, email, last_login_at
  FROM users
 WHERE auth_user_id IS NOT NULL
ON CONFLICT (provider, subject) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Devices
-- ---------------------------------------------------------------------------

CREATE TYPE device_platform AS ENUM ('ios', 'android', 'web');

CREATE TABLE devices (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid            NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  /* Stable per-installation id generated by the app. */
  install_id    text            NOT NULL,
  platform      device_platform NOT NULL,
  push_token    text,
  app_version   text,
  os_version    text,
  model         text,
  /* Set when the platform reports the token is no longer deliverable. */
  disabled_at   timestamptz,
  last_seen_at  timestamptz     NOT NULL DEFAULT now(),
  created_at    timestamptz     NOT NULL DEFAULT now(),
  updated_at    timestamptz     NOT NULL DEFAULT now(),
  CONSTRAINT devices_install_key UNIQUE (user_id, install_id)
);

-- A push token belongs to exactly one account: re-registering it elsewhere
-- must move it, never duplicate it.
CREATE UNIQUE INDEX devices_push_token_key
  ON devices (push_token) WHERE push_token IS NOT NULL;
CREATE INDEX devices_user_idx ON devices (user_id) WHERE disabled_at IS NULL;

CREATE TRIGGER devices_updated_at BEFORE UPDATE ON devices
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Notification preferences
--
-- Per-user, per-category opt-outs. Absence of a row means "send it" — the
-- operating system permission remains the outer gate.
-- ---------------------------------------------------------------------------

CREATE TABLE notification_preferences (
  user_id    uuid    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category   text    NOT NULL,
  push       boolean NOT NULL DEFAULT true,
  in_app     boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, category)
);

-- ---------------------------------------------------------------------------
-- Push delivery log
--
-- Only what is needed to diagnose delivery: never the notification body.
-- ---------------------------------------------------------------------------

CREATE TABLE push_deliveries (
  id              bigserial PRIMARY KEY,
  notification_id uuid        REFERENCES notifications (id) ON DELETE SET NULL,
  device_id       uuid        REFERENCES devices (id) ON DELETE SET NULL,
  status          text        NOT NULL CHECK (status IN ('sent', 'failed', 'skipped')),
  provider        text        NOT NULL,
  error_code      text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX push_deliveries_created_idx ON push_deliveries (created_at DESC);

-- ---------------------------------------------------------------------------
-- Calendar feeds
--
-- A resident may subscribe their phone's calendar to their schedule. The token
-- is the credential, so it is stored hashed and can be rotated.
-- ---------------------------------------------------------------------------

CREATE TABLE calendar_feeds (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resident_id  uuid        NOT NULL REFERENCES residents (id) ON DELETE CASCADE,
  token_hash   text        NOT NULL UNIQUE,
  revoked_at   timestamptz,
  last_fetched_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX calendar_feeds_one_active_per_resident
  ON calendar_feeds (resident_id) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- Account deletion
--
-- Deleting an account is not the same as erasing a schedule. A request is
-- recorded, the account is anonymised, and the operational record of who
-- covered which shift survives — see docs/DATA_RETENTION.md.
-- ---------------------------------------------------------------------------

CREATE TABLE account_deletion_requests (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        REFERENCES users (id) ON DELETE SET NULL,
  requested_by  uuid        REFERENCES users (id) ON DELETE SET NULL,
  email_at_request text     NOT NULL,
  reason        text,
  status        text        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'completed', 'cancelled')),
  requested_at  timestamptz NOT NULL DEFAULT now(),
  completed_at  timestamptz,
  notes         text
);

CREATE INDEX account_deletion_requests_status_idx
  ON account_deletion_requests (status, requested_at);

ALTER TABLE users ADD COLUMN anonymised_at timestamptz;
