import { loadScheduleSnapshot } from "@/server/domain/constraints/snapshot";
import { generateSchedule } from "@/server/domain/generator/generate";
import { assignmentsToRecords } from "@/server/domain/generator/source";
import { validationFailed } from "@/server/http/errors";
import type { ScheduleRecord, ScheduleSource } from "./types";

/**
 * The generator, as a source of schedule records.
 *
 * This is what makes a generated schedule and an imported one the same kind of
 * thing downstream. Both arrive as flat rows; both are validated by
 * `validateImport`; both are written by the same commit path. The generator
 * gets no private route into the schedule model, which matters because the
 * second route into a model is always the one that misses the rule the first
 * one grew last month.
 *
 * It is `configured: false` when a programme has no coverage requirements,
 * because a generator with nothing to satisfy would produce an empty schedule
 * and call it a success — the same honesty the invitation transport applies to
 * having no mail server.
 */
export interface GeneratedScheduleInput {
  program: { id: string; name: string; timezone: string };
  period: { start: string; end: string };
  seed?: number;
  timeBudgetMs?: number;
}

export const generatedSource: ScheduleSource<GeneratedScheduleInput> = {
  id: "generated",
  label: "Generated by ShiftSwitch",
  description:
    "Build a draft from your coverage requirements, cohorts and rules. The result is checked against every hard constraint before you see it.",
  configured: true,

  async fetch(input: GeneratedScheduleInput): Promise<ScheduleRecord[]> {
    const snapshot = await loadScheduleSnapshot(input.program, {
      period: input.period,
    });
    if (snapshot.coverage.length === 0) {
      throw validationFailed(
        "This programme has no coverage requirements, so there is nothing to generate against. " +
          "Say how many people each service needs under Services first.",
      );
    }

    const result = generateSchedule(
      { ...snapshot, assignments: [] },
      {
        period: input.period,
        seed: input.seed ?? 1,
        timeBudgetMs: input.timeBudgetMs ?? 0,
        locks: [],
        existing: [],
      },
    );

    if (!result.feasible) {
      /* A source that returned a partial schedule would have it imported and
         published by somebody who did not read the warning. */
      throw validationFailed(
        result.report.relaxations[0]?.message ??
          "No schedule satisfying this programme's rules could be built for that period.",
        { relaxations: result.report.relaxations, unfilled: result.report.unfilled.length },
      );
    }

    return assignmentsToRecords(result.assignments, snapshot);
  },
};
