import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy policy",
  robots: { index: true, follow: true },
};

/**
 * The privacy policy.
 *
 * It is written to match what the code actually does — the same audit that
 * produced APPLE_APP_PRIVACY_DECLARATION.md and GOOGLE_PLAY_DATA_SAFETY.md. If
 * the app starts collecting something new, all three change together.
 *
 * The placeholders in the "Who we are" section are the only things a deploying
 * institution must fill in; everything else is a statement about the software.
 */
const EFFECTIVE_DATE = "1 August 2026";

export default function PrivacyPolicyPage() {
  return (
    <article>
      <h1 className="mb-1 text-3xl font-bold text-ink">Privacy policy</h1>
      <p className="text-sm text-ink-subtle">Effective {EFFECTIVE_DATE}</p>

      <h2>The short version</h2>
      <p>
        ShiftSwitch helps resident physicians swap work shifts with each other.
        To do that it needs to know who you are, which program you belong to,
        and which shifts you are assigned. That is essentially all it holds.
      </p>
      <ul>
        <li>
          <strong>No patient information.</strong> ShiftSwitch is not a clinical
          system. It has no field for patient data and no interface to any
          clinical system. Do not enter patient information into it.
        </li>
        <li>
          <strong>No advertising, no tracking, no analytics SDKs.</strong> The
          app contains no third-party advertising, attribution, or analytics
          library. Nothing about you is sold, shared for advertising, or linked
          to data from other companies.
        </li>
        <li>
          <strong>No location, camera, microphone, contacts or photos.</strong>{" "}
          The app does not request those permissions because it has no feature
          that uses them.
        </li>
        <li>
          <strong>Your program can see your shifts.</strong> That is the point:
          your co-residents see shifts posted for switching, and your chief
          residents and program administrators see your schedule and your
          switches.
        </li>
      </ul>

      <h2>Who we are</h2>
      <p>
        ShiftSwitch is operated by your residency program or its institution,
        which is the controller of your information. Contact details for the
        operator, including the person responsible for privacy questions, are
        published by your program alongside the sign-in instructions it gave
        you. If you cannot find them, ask your program coordinator.
      </p>

      <h2>What we collect, and why</h2>

      <h3>Your identity</h3>
      <p>
        Your name, work email address and profile picture, taken from the Google
        account you sign in with. We receive these from Google only after you
        approve the sign-in. We use them to identify you to your co-residents
        and to your program, and to address the notification email you send your
        coordinator after a switch. We never receive your password.
      </p>

      <h3>Your schedule and switches</h3>
      <p>
        The shifts assigned to you, the shifts you post for switching, the
        offers you make and receive, and the completed switches you take part
        in — including which program rules were checked and who approved them.
        This is the record your program relies on to know who is responsible for
        each shift.
      </p>

      <h3>Your device, if you turn on notifications</h3>
      <p>
        If you allow notifications, we store a push token issued by Apple or
        Google, an identifier generated by the app for this installation, and
        the device model, operating system version and app version. We use them
        only to deliver notifications and to help diagnose a delivery failure.
        We do not use an advertising identifier and cannot derive one.
      </p>

      <h3>Technical and security logs</h3>
      <p>
        Sign-ins, sign-outs, permission failures and errors are logged with a
        timestamp and the account involved, and every change to the schedule is
        recorded in an audit log. These are used to keep the service secure and
        to let your program reconstruct what happened to a shift.
      </p>

      <h2>What we do not collect</h2>
      <ul>
        <li>Patient information of any kind.</li>
        <li>Your location, at any granularity.</li>
        <li>Contacts, photos, calendars on your device, or files.</li>
        <li>Your mailbox. The program notification email is composed by
          ShiftSwitch and handed to your own mail app; we never see whether or
          what you send.</li>
        <li>Any advertising or cross-app tracking identifier.</li>
        <li>Health information about you, beyond the fact that a leave-related
          rule may have prevented a switch. We do not store a reason for leave.</li>
      </ul>

      <h2>Who your information is shared with</h2>
      <ul>
        <li>
          <strong>Other residents in your program</strong> see your name, your
          training level, and any shift you post for switching or offer.
        </li>
        <li>
          <strong>Chief residents and program administrators</strong> see your
          schedule, your switches, and the audit history, because they are
          responsible for the schedule.
        </li>
        <li>
          <strong>Apple and Google</strong> receive a push token and the
          notification text when we send you a notification, because they
          operate the delivery networks. Google also handles your sign-in.
        </li>
        <li>
          <strong>The institution&rsquo;s hosting and database provider</strong>{" "}
          stores the data on the operator&rsquo;s behalf under contract.
        </li>
      </ul>
      <p>
        We do not sell your information, and we do not share it for advertising
        or for anyone else&rsquo;s marketing.
      </p>

      <h2>Your calendar link</h2>
      <p>
        If you create a calendar subscription, the link contains a secret token
        that lets any calendar app read your shift times without signing in. We
        store only a hash of that token, so we cannot show it to you again — and
        anyone you give the link to can read your schedule. You can replace or
        switch off the link at any time in Settings, which stops the old one
        working immediately.
      </p>

      <h2>How long we keep it</h2>
      <p>
        Your account and personal details are kept while your account is active.
        Completed switches, shift assignments and audit entries are kept for as
        long as your program needs them as an operational and accreditation
        record — see{" "}
        <a
          className="text-brand-ink underline"
          href="https://github.com/rosario608/Shiftswitch/blob/main/docs/DATA_RETENTION.md"
        >
          the retention policy
        </a>{" "}
        for the detail. Push tokens are deleted when you sign out, turn
        notifications off, or the platform tells us the token is dead.
      </p>

      <h2>Deleting your account</h2>
      <p>
        You can delete your account from inside the app: <em>You → Delete my
        account</em>. The app shows you exactly what is removed and what is kept
        before you confirm.
      </p>
      <p>
        Deleting removes your name, email address, profile picture, sign-in
        identities, registered devices, notification preferences, in-app
        notifications and calendar link, and ends your access immediately. What
        remains is the operational record: completed switches, who worked each
        shift, and the audit history — attached to an anonymised resident record
        with your name and email removed. Your program cannot lose the record of
        who was responsible for a shift because someone uninstalled an app.
      </p>
      <p>
        Deletion is blocked while you are still assigned to an upcoming shift or
        have a live switch posted; the app tells you which, so your program can
        reassign them first.
      </p>

      <h2>Your rights</h2>
      <p>
        Depending on where you live you may have the right to access, correct,
        export, restrict or object to the processing of your information, and to
        complain to a data protection authority. Deletion and access to your own
        schedule are built into the app; for anything else, contact your program
        administrator, who can act on it or pass it to the institution&rsquo;s
        privacy office.
      </p>

      <h2>Security</h2>
      <p>
        All traffic is encrypted in transit. Sign-in uses your institution&rsquo;s
        Google account; ShiftSwitch never handles a password. Session tokens are
        stored on the server only as hashes, and on your phone in the platform
        keychain. Authorisation is enforced on the server for every request — the
        app cannot grant itself a role.
      </p>

      <h2>Children</h2>
      <p>
        ShiftSwitch is for resident physicians and program staff. It is not
        directed at children and we do not knowingly collect information from
        anyone under 16.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes in a way that affects what we collect or who sees
        it, we will notify you in the app before the change takes effect.
      </p>
    </article>
  );
}
