import webpush from "web-push";
import { logger } from "@/server/observability/logger";
import type { PushMessage, PushResult, PushTarget, PushTransport } from "./push";

/**
 * Notifications to a browser, with no app store and no third-party account.
 *
 * ## Why this exists beside the Firebase transport rather than instead of it
 *
 * They reach different people. Firebase reaches a phone that installed the
 * native app from a store; this reaches a browser. A programme running the
 * website — which is what an enrollment link opens — has no native app at all,
 * so before this existed the honest answer to "will a resident be told
 * somebody offered on their shift" was *no*, and no amount of Firebase
 * configuration would have changed it.
 *
 * ## What it needs, and what it does not
 *
 * A VAPID keypair, generated by `npm run push:keys` and pasted into the
 * environment. That is the whole of it: no account, no billing relationship,
 * nothing to be approved for. The keypair identifies *this server* to Apple's,
 * Google's and Mozilla's push services; the browser vouches for the user by
 * handing over a subscription. Nobody in that chain has to know who we are.
 *
 * ## The iOS rule that shapes everything above this layer
 *
 * Safari delivers web push **only to a site the user has added to their Home
 * Screen**. A tab cannot receive one, ever, whatever this code does. So the
 * interface must never tell somebody browsing in a tab on an iPhone that they
 * will be notified — see `useWebPush` and the install prompt, which exist
 * because of this paragraph.
 *
 * ## Why `web-push` rather than our own encryption
 *
 * The payload is encrypted to the browser's key under RFC 8291, and getting
 * that subtly wrong does not raise an error — it produces a notification that
 * never arrives, on somebody else's device, with nothing in our logs. That is
 * the worst debugging shape there is. The library is the reference
 * implementation and the encryption is not where this product adds anything.
 */

export interface VapidKeys {
  publicKey: string;
  privateKey: string;
  /** `mailto:` or an https URL, so a push service can report abuse to somebody. */
  subject: string;
}

export function vapidKeysFromEnv(
  env: Record<string, string | undefined> = process.env,
): VapidKeys | null {
  const publicKey = env.VAPID_PUBLIC_KEY;
  const privateKey = env.VAPID_PRIVATE_KEY;
  if (!publicKey || !privateKey) return null;
  return {
    publicKey,
    privateKey,
    /* A default rather than a requirement: the spec wants a contact, and a
       deployment that has not set one should still be able to send. */
    subject: env.VAPID_SUBJECT ?? "mailto:support@shiftswitch.invalid",
  };
}

/**
 * Which failures mean "never try this subscription again".
 *
 * `404` and `410` are the push service saying the subscription is gone — the
 * browser was uninstalled, the site data cleared, permission revoked. Anything
 * else might be transient and must not disable a resident's notifications on
 * one bad night.
 */
function isPermanent(statusCode: number | undefined): boolean {
  return statusCode === 404 || statusCode === 410;
}

export class WebPushTransport implements PushTransport {
  readonly name = "webpush";
  readonly configured = true;

  constructor(private readonly keys: VapidKeys) {}

  async send(target: PushTarget, message: PushMessage): Promise<PushResult> {
    if (!target.keys) {
      /* A web target with no keys is a row that predates this feature or a
         half-finished subscribe. It cannot be encrypted to, and pretending
         otherwise would record a delivery that never happened. */
      return {
        deviceId: target.deviceId,
        status: "failed",
        errorCode: "missing_subscription_keys",
        permanentFailure: true,
      };
    }

    try {
      await webpush.sendNotification(
        {
          endpoint: target.token,
          keys: { p256dh: target.keys.p256dh, auth: target.keys.auth },
        },
        JSON.stringify({
          title: message.title,
          body: message.body,
          route: message.route,
          category: message.category,
          notificationId: message.notificationId,
        }),
        {
          vapidDetails: {
            subject: this.keys.subject,
            publicKey: this.keys.publicKey,
            privateKey: this.keys.privateKey,
          },
          /* Long enough to survive a phone that is off overnight, which is
             most of the audience for a schedule change. */
          TTL: 12 * 60 * 60,
        },
      );
      return { deviceId: target.deviceId, status: "sent" };
    } catch (error) {
      const status = (error as { statusCode?: number }).statusCode;
      const permanent = isPermanent(status);
      /* The endpoint is a URL identifying one browser; it is not logged. The
         status code is the whole of what an operator needs. */
      logger.warn("push.web_failed", {
        deviceId: target.deviceId,
        statusCode: status ?? null,
        permanent,
      });
      return {
        deviceId: target.deviceId,
        status: "failed",
        errorCode: status ? `http_${status}` : "unknown",
        permanentFailure: permanent,
      };
    }
  }
}

/**
 * One transport that sends each device by the route that can actually reach it.
 *
 * `sendPush` fans out over a user's devices without caring what they are, which
 * was right when there was one kind. A resident may now have a browser on a
 * laptop and, later, the app on a phone; a single transport for both would have
 * to guess, and guessing wrong means a notification that silently goes nowhere.
 */
export class RoutingPushTransport implements PushTransport {
  readonly name = "routing";

  constructor(
    private readonly web: PushTransport,
    private readonly native: PushTransport,
  ) {}

  get configured(): boolean {
    return this.web.configured || this.native.configured;
  }

  async send(target: PushTarget, message: PushMessage): Promise<PushResult> {
    const transport = target.platform === "web" ? this.web : this.native;
    const result = await transport.send(target, message);
    /* The delivery row records which service was actually asked, not the fact
       that a router was in the way — otherwise every row says "routing" and the
       question "did Apple accept it" has no answer. */
    return { ...result, provider: transport.name };
  }
}
